FROM amd64/python:3.7-slim-buster

RUN mkdir /models_temp && chmod 777 -R /models_temp
RUN mkdir /model_volume && chmod -R 777 /model_volume

COPY /models/ /models_temp/

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY main.py ./
COPY ./move_models.sh ./
RUN chmod a+x ./move_models.sh


ENTRYPOINT [ "./move_models.sh" ]