FROM amd64/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

RUN apt-get update
RUN apt-get install iputils-ping -y

CMD [ "python3", "-u", "./main.py" ]